baseURL = "https://ait-brainlab.github.io/"
languageCode = "en-us"
theme = "chaklam"
publishDir = "docs"

title = "AIT Brain Lab"

[params]
    logo = "/img/logo.png"

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
  params = { section='#hero' }
[[menu.main]]
  name = 'Members'
  pageRef = '/members'
  weight = 20
[[menu.main]]
  name = 'Projects'
  pageRef = '/Projects'
  weight = 30
[[menu.main]]
  name = 'Research Guide'
  pageRef = '/researchguide'
  weight = 40
[[menu.main]]
  name = 'Publications'
  pageRef = '/publications'
  weight = 50
[[menu.main]]
  name = 'Archives'
  pageRef = '/archives'
  weight = 60
[[menu.main]]
  name = 'Contact'
  pageRef = '/'
  weight = 70
  params = { section='#contact' }

[taxonomies]
  role = 'roles'

# https://gohugo.io/getting-started/configuration/