baseURL = "https://ait-brainlab.github.io/"
languageCode = "en-us"
theme = "chaklam"
publishDir = "docs"

title = "AIT Brain Lab"

[params]
    logo = "/img/logo.png"

# https://gohugo.io/getting-started/configuration/
